project:
  type: website
  output-dir: docs

website:
  title: "ggplot2 gallery"
  sidebar:
    style: "docked"
    search: true
    border: true
    contents:
      - section: "Welcome"
        contents:
          - index.qmd
      - section: "Univariate"
        contents:
          - uni/bar_graphs.qmd
          - uni/histograms.qmd
          - uni/frequency_polygons.qmd
          - uni/dot_plots.qmd
          - uni/density_plots.qmd
          - uni/violin_plot.qmd
          - uni/box_plots.qmd
      - section: "Amounts"
        contents:
          - amt/sum_bar_graphs.qmd
          - amt/grp_bar_graphs.qmd
          - amt/overlapping_bar_graphs.qmd
          - amt/waffle_chart.qmd
          - amt/heatmaps.qmd
          - amt/cleveland_dot_plots.qmd
      - section: "Proportions"
        contents:
          - prp/pie_charts.qmd
          - prp/diverging_bar_graphs.qmd
          - prp/mosaic_plot.qmd
          - prp/treemaps.qmd
          - prp/stacked_filled_density_graphs.qmd
          - prp/stream_plots.qmd
      - section: "Distributions"
        contents:
          - dist/overlapping_histograms.qmd
          - dist/overlapping_frequency_polygons.qmd
          - dist/overlapping_dot_plots.qmd
          - dist/bee_swarm_plots.qmd
          - dist/overlapping_stacked_density_plots.qmd
          - dist/ridgeline_plots.qmd
          - dist/grouped_box_plots.qmd
          - dist/grouped_violin_plots.qmd
          - dist/raincloud_plots.qmd
      - section: "Relationships"
        contents:
          - rela/scatter_plot.qmd
          - rela/grouped_scatter_plots.qmd
          - rela/bubble_charts.qmd
          - rela/grouped_bubble_charts.qmd
          - rela/line_graphs.qmd
          - rela/alluvial_charts.qmd
          - rela/parallel_sets.qmd
          - rela/bump_charts.qmd
          - rela/slope_graphs.qmd
          - rela/density_contours.qmd
          - rela/bins_2d.qmd
          - rela/hex_bins.qmd
          # - rela/correlograms.qmd
      - section: "Lines"
        contents:
          - geoms/geom_path.qmd
          - geoms/geom_line.qmd
          - geoms/geom_step.qmd
      - section: "Complex lines"
        contents:
          - geoms/geom_curve.qmd
      - section: "Areas"
        contents:
          - geoms/geom_ribbon.qmd


format:
  html:
    dpi: 320
    fig-format: retina
    fig-asp: 0.618
    toc: true
    code-fold: true
    code-tools: true
    toc-location: left
    toc-title: Contents
    html-math-method: katex
    css: styles.css
    theme:
      light: materia
      dark: superhero
      
editor: source



